name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        env:
          FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            export PATH=/home/ubuntu/.nvm/versions/node/v23.11.1/bin:$PATH
            cd GaRutinBE
            git pull
            rm -f tsconfig.build.tsbuildinfo
            npm install
            npm run build
            pm2 restart garutin-be
            pm2 save
